[build]
  publish = "build/web"
  command = "echo 'Sube la carpeta build/web manualmente o via CI'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
